name: Build and deploy to production

on: 
  push:
    branches: 
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    
    steps:
    - name: Checkout GitHub Actions
      uses: actions/checkout@main
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Test with pytest
      run: |
        pip install pytest httpx
        pytest test_api.py 
      
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: pretadepenser.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
     
     
    - name: Build and push container image to registry 
      run: |
        docker build . -t pretadepenser.azurecr.io/pret-a-depenser-api:${{ github.sha }}
        docker push pretadepenser.azurecr.io/pret-a-depenser-api:${{ github.sha }}
        
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pret-a-depenser'
        images: 'pretadepenser.azurecr.io/pret-a-depenser-api:${{ github.sha }}'
        slot-name: 'staging'
        
        
    - name: Azure logout
      run: |
        az logout